apiVersion: v1
kind: Service
metadata:
  name: gofer
  namespace: gofer
  labels:
    app.kubernetes.io/name: gofer
spec:
  selector:
    app.kubernetes.io/name: gofer
  ports:
    - name: http
      port: 8080
      targetPort: http
